### ISSUE TITLE
Contributing Documentation

### ISSUE THREAD

**Issue by ariomoklo** [papang/prouds2ui#1]
### Task: Membuat Dokumen Kontribusi berisi Development Guidelines

Konten dari dokumen kontribusi:
- [x] Code Style Guidelines
- [x] Git Branch - Commit Guidelines / Format
- [x] Git Issue  Guidelines

> 📓 Note: 
> Code Style Guidelines aku buat menyesuaikan seperti yang biasa aku buat. Jika ingin ada tambahan bisa langsung edit CONTRIBUTING.md atau dibicarakan pada Issue ini.

@fa3af  @papang

**Comment by ariomoklo** [comment]
[📜 CONTRIBUTION DOCUMENT](https://github.com/papang/prouds2ui/blob/master/CONTRIBUTING.md)
